package ogam1014;

public enum Tile{
	TL, T, TR, WATERBORDER_TL, WATERBORDER_T, WATERBORDER_TR,
	TTL, TT, TTR, WATERBORDER_L, GRASS, WATERBORDER_R,
	L, GRASS2, R, WATERBORDER_BL, WATERBORDER_B, WATERBORDER_BR
}
