package ogam1014;

import java.awt.Point;

public enum Tile{
	TL, T, TR, WATERBORDER_TL, WATERBORDER_T, WATERBORDER_TR,TTdL, TdT, TddTR, WdATERBORDER_L, GRdASS, WATdERBORDER_R,DD,DR,DL,
	TTL, TT, TTR, WATERBORDER_L, aTT, WATERBORDER_R,L, GRASS2, R, WATERBORDER_BL, WATERBORDER_B, WATERBORDER_BR,RR,RRR,RRRRR,
	TLa, aT, TaR, WATaERBORDER_TL, WATERaBORDER_T, WATERBORaDER_TR,TaTL, GRASS, aTTR, WATERBOaRDER_L, GRaASS, WATEaRBORDER_R,
	La, GaRASS2, aR, WAaTERBORDER_BL, WATaERBORDER_B, WATERaBORDER_BR,TgL, Tg, TRg, WATERBORDEgR_TL, WATgERBORDER_T, WATERBgORDER_TR,
	TTgL, gTT, gTTR, WATERBgORDER_L, GRAgSS, WATERBORDEgR_R,TxL, Tx, TxR, WATxERBORDER_TL, WATERBxORDER_T, WATERxBORDER_TR,TTxdL, TxdT, TddTxR, WdATERBORDxER_L, GRdxASS, WATdExRBORDER_R,xDD,DxR,DxL,
	xTTL, TTx, xTTR, WATERxBORDER_L, GRxASS, WATERxBORDER_R,Lx, GRASxS2, Rx, WATERBOxRDER_BL, WATERxBORDER_B, WATxERBORDER_BR,RxR,RxRR,RRxRRR,
	TLxa, axT, TaxR, WATaERBORDExR_TL, WATERaBORDERx_T, WATERBORaDExR_TR,TaTxL, xaTT, aTxTR, WATERBOaRDExR_L, GRaASxS, WATEaRBORDExR_R,ROx,ROxO,ROxOR,
	xLa, GaxRASS2, aRx, WAaTxERBORDER_BL, WATaERBOxRDER_B, WATERaBORDxER_BR,TgLx, Txg, TRxg, WATExRBORDEgR_TL, WATgERBORDER_xT, WATERBgORDxER_TR,Rs,D,C,
	VOID;

	public static final int SIZE = 16;
	
	public boolean isWall() {
		return this == TL
			|| this == TR
			|| this == T
			|| this == VOID;
	}
	
	public static Point convertToTilePos(double x, double y){
		return new Point((int) (x / SIZE), (int) (y / SIZE));
	}
}